// Generated by https://quicktype.io

export interface Forecast {
    current: Current;
    daily: DailyHourly[];
    hourly: DailyHourly[];
}

export interface Current {
    time: string;
    temperature: number;
    humidity: number;
    feels_like: number;
    precipitation: number;
    rain: number;
    showers: number;
    snowfall: number;
    weather_code: number;
    pressure: number;
    uv_index: number;
    us_aqi: number;
}

export interface DailyHourly {
    time: string;
    temperature: number;
    precipitation_probability: number;
    weather_code: number;
}
